config/routes.rb
Rails.application.routes.draw do
  root "teams#index"
  get 'portfolios/index'
  get 'contacts/index'
  get 'contacts/new'
  post 'contacts/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, status: "仕事の相談"}, {id: 2, status: "遊びのお誘い"},{id: 3, status: "その他"}
  ]

  include ActiveHash::Associations
  has_many :contacts

end

app/models/client.rb
class Client < ApplicationRecord

  has_many :contacts
  accepts_nested_attributes_for :contacts, allow_destroy: true  # fields_for（後述）に必要

  validates :nickname, :email, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  validates :message, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def new
    @client = Client.new
    @contact = @client.contacts.new
  end

  def create
    @client = Client.new(client_params)
    # @contact = Contact.new(contact_params)
    if @client.save
      redirect_to root_path, notice: 'メッセージを送信しました'
    else
      flash.now[:alert] = "必須情報が不足しています"
      render :new
    end
  end

  private

  def client_params
    params.require(:client).permit(
      :nickname,
      :email,
      contacts_attributes: [:category_id, :message, :_destroy, :id]
    )
  end

  # def contact_params
  #   params.require(:contact).permit(
  #     :client_id,
  #     :category_id,
  #     :message,
  #   )
  # end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.haml
.wrapper
  = render "teams/top_header"

  .title
    -# .title__word
    Contact
  .form-area
    = form_with model: @client, url: contacts_create_path, local: true do |f|
      .form-area__nickname
        = f.label "ニックネーム", class: 'category'
        = f.label "必須", class: 'required'
        = f.text_field :nickname, class: 'text_field', placeholder: '全角入力'
      .form-area__email
        = f.label "メールアドレス", class: 'category'
        = f.label "必須", class: 'required'
        = f.email_field :email, class: 'text_field', placeholder: 'E-mail'
      = f.fields_for :contacts do |contact|  # 別のモデルのフォームはfield_forメソッドを使う
        .form-area__category
          = contact.label "相談の種類", class: 'category'
          = contact.label "必須", class: 'required'
          = contact.collection_select :category_id, Category.all, :id, :status, {prompt: "選択してください"}, {class: "category_form", id: "category_id"}
          = contact.text_area :message, maxlength: 1000, placeholder: '全角入力', class: 'text_area'
      .Button
        = f.submit "送信する", class: "Button__submit"

  .futer
    = render "teams/bottom_footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SalesPromotion
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/portfolios/index.html.haml
.wrapper
  = render "teams/display_btn"
  = render "teams/top_header"

  .title
    -# .title__word
    Portfolio
  .portfolio-area1
    = link_to "アプリ１", "#", class:'links';
  .futer
    = render "teams/bottom_footer"